name = "Moulidoudou"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ace8b99c2aab7a5df0151eddb3a037fb25d01a87bb50bd9ea02eb53f7fea3556"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
