name = "Moulidoudou"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30ab414d24798245f2aba48ed69c94aad6e72cc6cb218eb921ddcfa4356a776a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
