name = "Moulidoudou"
author = "MmeCromatique"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef6dd4df6d46851bfd4a50ae8825290e7f39b64e6f182acb03098b3591e6eacc"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
unsup = "1.1.6"
