[flavor_groups.rendering_mod]
name = "Qualite Graphique"
description = "Voulez-vous des shaders ?"
side = "client"
[[flavor_groups.rendering_mod.choices]]
id = "iris"
name = "Iris"
description = "Installer Iris pour les shaders et effets lumineux (Gourmand en Carte Graphique)"
[[flavor_groups.rendering_mod.choices]]
id = "no_rendering_mods"
name = "Rien"
description = "Pas de mods de Shaders"
[flavor_groups.distant_horizons]
name = "Distance de rendu"
side = "both"
description = "Ameliore la distance de rendu"
[[flavor_groups.distant_horizons.choices]]
id = "distant-horizons"
name = "Distant Horizons"
description = "Installer Distant Horizons qui permet une plus grande distance d'affichage (Gourmand en Processeur)."
[[flavor_groups.distant_horizons.choices]]
id = "no_distant_horizons"
name = "Rien"
description = "Pas de mods de distance d'affichage"